spring:
  application:
    name: ${APPLICATION_NAME:Snowflake ID Generator Local}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: snowflake
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog.xml

snowflake-settings:
  starting-epoch: ${STARTING_EPOCH:946684800}
  datacenter-id: ${DATACENTER_ID:1}
  worked-id: ${WORKED_ID:1}

kubernetes-settings:
  pod-name: ${POD_NAME:local}

management:
  endpoints:
    web:
      base-path: /management
      path-mapping:
        health: health
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
