# fluentd-config-working.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*snowflake*.log
      pos_file /fluentd/pos/snowflake.pos
      tag snowflake
      read_from_head true
      follow_inodes true
      <parse>
        @type none
      </parse>
    </source>

    <match snowflake>
      @type stdout
    </match>
