#volumes:
#  postgres_data:

services:
  postgres:
    image: postgres:14
    volumes:
      - ./datas/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -c 'max_connections=500'
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
